services:
  squid:
    # image: docker.io/salrashid123/squidproxy
    platform: linux/amd64
    build:
      context: .
    # command: /apps/squid/sbin/squid -f /apps/squid.conf -NYCd 1
    entrypoint: /apps/entrypoint.sh
    ports:
      - "3128:3128"
    environment:
      - P001_USER="moclojer:${P001_USER}"
      - P001_PASS="moclojer:${P001_PASS}"
      - P001_PORT="3128:${P001_POST}"
    volumes:
      - ./squid.conf:/apps/squid.conf.template
      - ./htpasswd:/apps/htpasswd
