version: "3"
services:
  squid:
    # platform: linux/amd64
    build:
      context: .
    # command: /apps/squid/sbin/squid -f /apps/squid.conf -NYCd 1
    # entrypoint: /etc/squid/entrypoint.sh
    ports:
      - "${P001_PORT:-3128}:3128"
    environment:
      - P001_USER=${P001_USER}
      - P001_PASS=${P001_PASS}
